// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token = '';
    try {
      token = localStorage.getItem("token") || '';
    } catch {}
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
